Практические задания

In [1]:
import numpy as np

# Создаем массив 3x3 с числами от 1 до 9
arr = np.arange(1, 10).reshape(3, 3)

# Умножаем все элементы на 2
arr *= 2

# Заменяем элементы больше 10 на 0
arr[arr > 10] = 0

print(arr)

[[ 2  4  6]
 [ 8 10  0]
 [ 0  0  0]]


In [4]:
import numpy as np

# Создаем массив из 20 случайных целых чисел от 1 до 100
arr = np.random.randint(1, 101, 20)

# Находим и выводим элементы, кратные 5
divisible_by_5 = arr[arr % 5 == 0]
print("Элементы, кратные 5:", divisible_by_5)

# Заменяем элементы кратные 5 на -1
arr[arr % 5 == 0] = -1

# Выводим обновленный массив
print("Обновленный массив:", arr)

Элементы, кратные 5: [65 15 65 45 60 85]
Обновленный массив: [13 38 31 12 67 -1 37 -1 81 -1 38 58 88 -1 -1 -1 52 31 66 91]


In [7]:
import numpy as np

# Создаем два массива 1x5 со случайными числами от 0 до 50
arr1 = np.random.randint(0, 51, (1, 5))
arr2 = np.random.randint(0, 51, (1, 5))

# Объединяем по строкам в массив 2x5
combined = np.vstack((arr1, arr2))

# Разделяем на два массива по 5 элементов каждый
split1 = combined[0, :]  # Первая строка (5 элементов)
split2 = combined[1, :]  # Вторая строка (5 элементов)

print("Первый исходный массив:\n", arr1)
print("Второй исходный массив:\n", arr2)
print("\nОбъединенный массив:\n", combined)
print("\nПервый разделенный массив:", split1)
print("Второй разделенный массив:", split2)

Первый исходный массив:
 [[ 2 40 22 13 13]]
Второй исходный массив:
 [[22 10 46 38 32]]

Объединенный массив:
 [[ 2 40 22 13 13]
 [22 10 46 38 32]]

Первый разделенный массив: [ 2 40 22 13 13]
Второй разделенный массив: [22 10 46 38 32]


In [10]:
import numpy as np

# Создаем массив из 50 равномерно распределенных чисел от -10 до 10
arr = np.linspace(-10, 10, 50)

# Вычисляем суммы
total_sum = np.sum(arr)
positive_sum = np.sum(arr[arr > 0])
negative_sum = np.sum(arr[arr < 0])

# Выводим результаты
print("Сумма всех элементов:", round(total_sum, 2))
print("Сумма положительных элементов:", round(positive_sum, 2))
print("Сумма отрицательных элементов:", round(negative_sum, 2))

Сумма всех элементов: 0.0
Сумма положительных элементов: 127.55
Сумма отрицательных элементов: -127.55


In [13]:
import numpy as np

# Создаем единичную матрицу 4x4
identity_matrix = np.eye(4)

# Создаем диагональную матрицу с заданными элементами
diagonal_matrix = np.diag([5, 10, 15, 20])

# Вычисляем суммы элементов
sum_identity = np.sum(identity_matrix)
sum_diagonal = np.sum(diagonal_matrix)

# Выводим результаты
print("Единичная матрица:\n", identity_matrix)
print("\nДиагональная матрица:\n", diagonal_matrix)
print("\nСумма элементов единичной матрицы:", sum_identity)
print("Сумма элементов диагональной матрицы:", sum_diagonal)
print("\nСравнение сумм:", 
      "Суммы равны" if sum_identity == sum_diagonal else "Суммы различны")

Единичная матрица:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Диагональная матрица:
 [[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]

Сумма элементов единичной матрицы: 4.0
Сумма элементов диагональной матрицы: 50

Сравнение сумм: Суммы различны


In [16]:
import numpy as np

# Создаем две матрицы 3x3 со случайными числами от 1 до 20
matrix1 = np.random.randint(1, 21, size=(3, 3))
matrix2 = np.random.randint(1, 21, size=(3, 3))

# Вычисляем операции
sum_matrix = matrix1 + matrix2
diff_matrix = matrix1 - matrix2
prod_matrix = matrix1 * matrix2

# Выводим результаты
print("Первая матрица:\n", matrix1)
print("\nВторая матрица:\n", matrix2)
print("\nСумма матриц:\n", sum_matrix)
print("\nРазность матриц (Первая - Вторая):\n", diff_matrix)
print("\nПоэлементное произведение:\n", prod_matrix)

Первая матрица:
 [[17  3 18]
 [20  9  8]
 [ 2 17  7]]

Вторая матрица:
 [[17  6 12]
 [17  7 15]
 [ 5  9 14]]

Сумма матриц:
 [[34  9 30]
 [37 16 23]
 [ 7 26 21]]

Разность матриц (Первая - Вторая):
 [[ 0 -3  6]
 [ 3  2 -7]
 [-3  8 -7]]

Поэлементное произведение:
 [[289  18 216]
 [340  63 120]
 [ 10 153  98]]


In [20]:
import numpy as np

# Создаем матрицы
matrix1 = np.random.randint(1, 11, size=(2, 3))
matrix2 = np.random.randint(1, 11, size=(3, 2))

# Выполняем матричное умножение
result = matrix1 @ matrix2  # Можно также использовать np.dot(matrix1, matrix2)

# Выводим результаты
print("Первая матрица (2x3):\n", matrix1)
print("\nВторая матрица (3x2):\n", matrix2)
print("\nРезультат умножения (2x2):\n", result)

Первая матрица (2x3):
 [[ 2 10  2]
 [ 7  3  8]]

Вторая матрица (3x2):
 [[ 6  3]
 [ 7 10]
 [ 5  2]]

Результат умножения (2x2):
 [[ 92 110]
 [103  67]]


In [25]:
import numpy as np

# Создаем случайную матрицу 3x3 с целыми числами от 1 до 10
matrix = np.random.randint(1, 10, size=(3, 3))

# Вычисляем определитель
det = np.linalg.det(matrix)

print("Исходная матрица:\n", matrix)
print("\nОпределитель матрицы:", round(det, 2))

# Проверяем обратимость матрицы (с учетом погрешности вычислений)
if not np.isclose(det, 0, atol=1e-6):
    # Вычисляем обратную матрицу
    inv_matrix = np.linalg.inv(matrix)
    print("\nОбратная матрица (округлено до 3 знаков):\n", np.round(inv_matrix, 3))
else:
    print("\nМатрица вырождена, обратной не существует")

Исходная матрица:
 [[9 5 4]
 [7 5 6]
 [4 1 6]]

Определитель матрицы: 74.0

Обратная матрица (округлено до 3 знаков):
 [[ 0.324 -0.351  0.135]
 [-0.243  0.514 -0.351]
 [-0.176  0.149  0.135]]


In [29]:
import numpy as np

# Создаем матрицу 4x4 со случайными числами от 1 до 50
matrix = np.random.randint(1, 51, size=(4, 4))

# Вычисляем транспонированную матрицу и след
transposed = matrix.T
trace = np.trace(matrix)

print("Исходная матрица:")
print(matrix)
print("\nТранспонированная матрица:")
print(transposed)
print("\nСлед матрицы:", trace)

Исходная матрица:
[[24  6 45  9]
 [35 30 40  6]
 [19 32 29 42]
 [ 8 35 29 21]]

Транспонированная матрица:
[[24 35 19  8]
 [ 6 30 32 35]
 [45 40 29 29]
 [ 9  6 42 21]]

След матрицы: 104


In [32]:
import numpy as np

# Создаем матрицу коэффициентов A
A = np.array([
    [2, 3, -1],
    [4, -1, 2],
    [-3, 5, 4]
])

# Создаем вектор правой части B
B = np.array([5, 6, -2])

# Решаем систему уравнений
solution = np.linalg.solve(A, B)

# Выводим результат
print("Решение системы:")
print(f"x = {solution[0]:.2f}")
print(f"y = {solution[1]:.2f}")
print(f"z = {solution[2]:.2f}")

Решение системы:
x = 1.64
y = 0.58
z = 0.01


Индивидуальное задание №5


In [ ]:
import numpy as np
A = np.array([
    [1, 1, 1],
    [-1, 1, 0],
    [0, -2, 1]])
b = np.array([100, 10, 0])
def cramer_solve(A, b):
    det_A = np.linalg.det(A)
    A_x = A.copy()
    A_x[:, 0] = b
    det_Ax = np.linalg.det(A_x)
    A_y = A.copy()
    A_y[:, 1] = b
    det_Ay = np.linalg.det(A_y)
    A_z = A.copy()
    A_z[:, 2] = b
    det_Az = np.linalg.det(A_z)
    x = det_Ax / det_A
    y = det_Ay / det_A
    z = det_Az / det_A
    return np.array([x, y, z])
cramer_solution = cramer_solve(A, b)
print("Решение методом Крамера:", cramer_solution)
def matrix_method_solve(A, b):
    A_inv = np.linalg.inv(A)
    x = A_inv @ b
    return x
matrix_solution = matrix_method_solve(A, b)
print("Решение матричным методом:", matrix_solution)
numpy_solution = np.linalg.solve(A, b)
print("Решение с помощью np.linalg.solve:", numpy_solution)